### ISSUE TITLE
Не подключены шрифты

### ISSUE THREAD

**Issue by mathetes** [rysev-a/gulp-bootstrap#1]
Попробовал подключить шрифты, но пока не хотят.
`gulp.task('fonts:copy', function() {
  return gulp.src('./assets/fonts/**/*.{eot,svg,ttf,woff,woff2}')
  .pipe(gulp.dest('./build/fonts/'));
});
`

**Comment by rysev-a** [comment]
Добавил задачу fonts:copy

**Comment by mathetes** [comment]
Спасибо, шрифты подключились
